version: "3.9"
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - flnet

  client1:
    build: ./client1
    depends_on:
      - server
    networks:
      - flnet

  client2:
    build: ./client2
    depends_on:
      - server
    networks:
      - flnet

  client3:
    build: ./client3
    depends_on:
      - server
    networks:
      - flnet

  client4:
    build: ./client4
    depends_on:
      - server
    networks:
      - flnet

  client5:
    build: ./client5
    depends_on:
      - server
    networks:
      - flnet

networks:
  flnet:
    driver: bridge
